name: quizzo
description: "Quizzo is a quiz platform which make student learn things thorugh MCQs."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  dartz: ^0.10.1
  get_it: ^8.0.2
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  lottie: ^3.1.3
  path_provider: ^2.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
